[server]
headless = true
enableCORS = true  # Changed from false to match enableXsrfProtection
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true
port = 8501

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true

[logger]
level = "info"

[client]
showErrorDetails = true